"$schema" = 'https://starship.rs/config-schema.json'

format = """
 $username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes \
$line_break\
$cmd_duration\
$jobs\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[fill]
symbol = " "

[git_branch]
format = "$symbol[$branch]($style)"
style = "bright-black"

[git_status]
format = """\
		  [\
		  [$staged](green)\
		  [$modified](red)\
		  [$conflicted$deleted](red)\
		  [$renamed](yellow)\
		  [$untracked](bright-black) \
		  ($ahead_behind$stashed)\
		  ]($style)
"""
style = "cyan"
up_to_date = ""
conflicted = "="
deleted ="-"
staged = "+"
renamed = "»"
diverged = "⇕"
modified = "~"
untracked = "*"
ahead = "⇡"
behind = "⇣"
stashed = "#"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[kubernetes]
symbol = 'k8s'
#format = '[[$symbol://$context/$namespace](fg:black bg:cyan)](fg:cyan bg:black) '
format = """\
[](fg:blue bg:black)[$symbol](fg:black bg:blue)[](fg:blue bg:bright-blue)\
[ $context](fg:black bg:bright-blue)[](fg:bright-blue bg:bright-white)\
[ $namespace](fg:black bg:bright-white)\
[](fg:bright-white bg:black)\
"""
detect_extensions = [ "k8s.yaml", "k8s" ]
disabled = false

[jobs]
symbol = "%"
style = "bold green"
