views:
  v1/pods:
    sortColumn: AGE:desc
    columns:
      - NAME
      - PF
      - AGE
      - READY
      - STATUS
      - RESTARTS
      - MEM
      - "%CPU/R"
  v1/services:
    columns:
      - NAME
      - AGE
      - TYPE
      - CLUSTER-IP
