# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMonoNL Nerd Font' style=Bold
bold_font        family='JetBrainsMonoNL Nerd Font' style=ExtraBold
italic_font      family='JetBrainsMonoNL Nerd Font' style='Bold Italic'
bold_italic_font family='JetBrainsMonoNL Nerd Font' style='ExtraBold Italic'
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
